### PR TITLE
Added python check in bash + pacman command to clear old caches

### PR DESCRIPTION
**Pull request by PardesiCat**
Hi i thinks  when using bash script meathod its better to check any python installed or not 
so i added the code in bash script 
mysugbash

> As you can see its showing all pythons location ( here i have anaconda for testing my pythons codes  include main arch python

2. suggestion a command with pacman which clear old caches and db  before update
 

> in my view  sometimes  old packages cache can make conflicts  like broken packages caches
 if those will be clean fresh update will be download by pacman. details in pic
pacmanpcat

### CODE REVIEW

**Comment by PardesiCat** [comment]
when python isnt installed or detected it will show like this 

note 

> For testing purposes, here I've included the code `python-test`, which isn't a valid command but still gets the job done without harming my Python environment.


test1
test2

**Comment by felipealfonsog** [comment]
you can install it via AUR ... with yay .... check the read me ...
and I'm working in a new. version ... wait for it please ...

**Review by felipealfonsog — CHANGES_REQUESTED** [review]
Thing is that this executes the python piece of software that makes possible update pacman and yay and brew on the fly .... not the bash ... actually I'm thinking in a bash installer rather than this. .. cause actually the installer via yay in AUR for Arch is working perfectly ....

**Review by felipealfonsog — APPROVED** [review]
I approved the PR ! but I've moved to the idea of having an installer in bash .. which is already in the repo.... although now I think we can keep this execute.sh ....

**Comment by felipealfonsog** [comment]
There's now a new version up and running in AUR ... 0.0.17 .... even cooler! ..

**Pull request merged**
